### ISSUE TITLE
cabal wrapper uses always global ghc in PATH 

### ISSUE THREAD

**Issue by jneira** [haskell/hie-bios#194] opened 2020-06-10 12:25 UTC
* detected when testing ghcide in itself (see https://github.com/digital-asset/ghcide/issues/610)
* although you set the field `with-compiler: ghc-8.6.5` in the `cabal.project` hie-bios was using my default ghc in path (ghc-8.8.3)
```
PS D:\dev\ws\haskell\ghcide> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
PS D:\dev\ws\haskell\ghcide> ghcide --version
ghcide version: 0.2.0 (GHC: 8.6.5) (PATH: D:\bin\ghcide.exe)
PS D:\dev\ws\haskell\ghcide> cat .\cabal.project
packages: .

with-compiler: ghc-8.6.5
PS D:\dev\ws\haskell\ghcide> cabal clean
PS D:\dev\ws\haskell\ghcide> ghcide
ghcide version: 0.2.0 (GHC: 8.6.5) (PATH: D:\bin\ghcide.exe)
Ghcide setup tester in D:\dev\ws\haskell\ghcide.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/4: Finding files to test in D:\dev\ws\haskell\ghcide
Found 63 files

Step 2/4: Looking for hie.yaml files that control setup
Found 3 cradles

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "D:\\dev\\ws\\haskell\\ghcide\\src\\Development\\IDE\\GHC\\WithDynFlags.hs"
> Resolving dependencies...
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - ghcide-0.2.0 (lib) (first run)
> Configuring library for ghcide-0.2.0..
> Preprocessing library for ghcide-0.2.0..
File:     D:\dev\ws\haskell\ghcide\src\Development\IDE\GHC\WithDynFlags.hs
Hidden:   no
Range:    1:0-100001:0
Source:   compiler
Severity: DsError
Message:
  <command line>: cannot satisfy -package-id aeson-1.5.1.0-1e42a0cdbd4b065e4d6f1c804d63f35706230918:
  aeson-1.5.1.0-1e42a0cdbd4b065e4d6f1c804d63f35706230918 is unusable due to missing dependencies:
  attoparsec-0.13.2.4-04e8dfec95c5fe0d96babd7d76d0463f6955b1db base-4.13.0.0
  base-compat-b_-0.11.1-1ae618f5c56712e963c7c424698817f24ad5c97a bytestring-0.10.10.0
```
* hypothesis:
  * the wrapper is calling "ghc" with no args for all invocations with no `--interactive`
https://github.com/mpickering/hie-bios/blob/293baaf793f82f639affe734ebe785ccdcafd40b/wrappers/cabal.hs#L19
  * cabal calls `ghc --numeric-version`, being "ghc" the programs passed in `-w` as first option, to know the actual ghc version in use
```
PS D:\dev\ws\haskell\ghcide> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.3
PS D:\dev\ws\haskell\ghcide> cat .\cabal.project
packages: .

with-compiler: ghc-8.6.5
PS D:\dev\ws\haskell\ghcide> cabal exec ghc -- --version
Resolving dependencies...
The Glorious Glasgow Haskell Compilation System, version 8.6.5
PS D:\dev\ws\haskell\ghcide> cabal exec ghc --with-compiler=ghc-8.8.3 -- --version
Resolving dependencies...
The Glorious Glasgow Haskell Compilation System, version 8.8.3
PS D:\dev\ws\haskell\ghcide>
```
  * so it is ignoring the original ghc used in by hie-bios (`ghcPath` [here ](https://github.com/mpickering/hie-bios/blob/master/src/HIE/Bios/Cradle.hs#L419))

Possible solutions:
* Use an intermmediate env var (`HIE_BIOS_WRAPPER_GHC`?) to inform the wrapper about the real ghc
* Pass a new argument to the wrapper `--hie-bios-ghc` and use it, removing it before calling the real ghc

**Comment by fendor** [comment] 2020-06-11 08:04
I can confirm the behaviour on linux, too.
The hypothesis seems to be correct! 

Possible fixes:
* Find the appropriate GHC version in Environment.hs (via cabal-install-parsers?) and pass it via an environment variable to the wrapper.
* Wait for cabal show-build-info to land (https://github.com/haskell/cabal/pull/6241) since it will fix all our problems.
  * Document why it doesn't work and how to work around it.

Unless a lot of users complain about this issue, I am in favour of the latter, as it will be just a few months and solve the issue for good. 
Any work-around will be code cruft very soon.

**Comment by jneira** [comment] 2020-06-11 09:06
Fair enough, moreover, cabal action uses global ghc in two points:
* the wrapper
* when compiling the wrapper itself, it usually does not throw any error cause the wrapper is dead simple code but it would throw it if you are using cabal but you dont have ghc in global path (nix?)

**Comment by fendor** [comment] 2020-06-12 20:17
I think this issue is related: https://github.com/mpickering/hie-bios/issues/148

**Comment by jneira** [comment] 2021-07-30 12:11
A nice workaround if you use ghcup was mentioned by @hasufell in irc: open a terminal in the project dir root and do `PATH=$(ghcup whereis -d ghc <ghc-ver>):$PATH &&  code . `

**Comment by hasufell** [comment] 2021-07-30 14:16
> Wait for cabal show-build-info to land (show-build-info (exe:cabal part plus tests) haskell/cabal#6241) since it will fix all our problems. 

That was one year ago...

**Comment by fendor** [comment] 2021-07-30 14:24
Back then it seemed like a reasonable expectation that it was going to be merged soon

**Comment by hasufell** [comment] 2021-07-30 14:53
> Back then it seemed like a reasonable expectation that it was going to be merged soon

The dream 
![NicePng_crying-meme-png_1801723](https://user-images.githubusercontent.com/1241845/127671481-63073e70-cc53-4c42-8d8f-b047a21bc7b5.png)

**Comment by jneira** [comment] 2021-07-30 15:06
> A nice workaround if you use ghcup was mentioned by @hasufell in irc: open a terminal in the project dir root and do `PATH=$(ghcup whereis -d ghc <ghc-ver>):$PATH &&  code . `

if you don't have ghcup you can do simply `PATH=$(cabal exec which -- ghc):$PATH &&  code . `

**Comment by jneira** [comment] 2021-07-30 15:08
> > Back then it seemed like a reasonable expectation that it was going to be merged soon
> 
> The dream 

third time is the right time

**Comment by hasufell** [comment] 2021-07-30 15:25
> A nice workaround if you use ghcup was mentioned by @hasufell in irc: open a terminal in the project dir root and do PATH=$(ghcup whereis -d ghc <ghc-ver>):$PATH && code . 

Here's a bash function for your .bashrc:

```sh
with_ghc() {
  local np=$(ghcup --offline whereis -d ghc $1)
  shift
  PATH="$np:$PATH" "$@"
}
```

And your your fish config:

```fish
function with_ghc
  set np (ghcup --offline whereis -d ghc $argv[1])
  PATH="$np:$PATH" $argv[2..-1]
end
```

**Comment by hasufell** [comment] 2021-09-09 09:39
Since the cabal patch is merged, I guess this can move forward

**Comment by fendor** [comment] 2021-09-09 11:17
Yep, but not quite ideal yet, as we still have no *quick* way of querying for the project ghc. Currently, it requires to build at least one cabal component.

**Comment by hasufell** [comment] 2021-09-09 11:19
> Currently, it requires to build at least one cabal component.

Well, that means if I run `cabal build` before starting the language server, it should work?

**Comment by fendor** [comment] 2021-09-09 11:22
if you launch the correct language server (e.g. 8.6.5 for projects that use 8.6.5) then it will work (assuming MR #301). But hls-wrapper will still pick up the wrong ghc version and launch the wrong language server.

**Comment by fendor** [comment] 2021-09-09 11:30
BTW, MR #301 is not correct currently, as it does not use the latest json lib decoder/encoder for build-info.

**Comment by jneira** [comment] 2021-11-09 13:35
The last promising hack to get the path to ghc could be:

```
cabal exec ghc -- -package-env=- -e 'System.Environment.getExecutablePath'
```

ugly but seems to work for now.

Talking with @fendor it seems i can be used in a more direct way than #282 so maybe it could be used in another smaller pr if i understood it correctly

**Closed** 2022-02-22 19:31 UTC
Labels: type: bug, can-workaround
